### ISSUE TITLE
POST operation without a request body failing

### ISSUE THREAD

**Issue by valcharry** [equinor/openapi-flattener#5]
I have an API that is defined that has a POST method but no request body and I'm seeing the following error.
```
/home/workspace/.npm/_npx/cb83394c13646cfe/node_modules/openapi-flattener/dist/flattener.js:36
    var bodySchema = (_a = requestBody.content['application/json']) === null || _a === void 0 ? void 0 : _a.schema;
                                       ^

TypeError: Cannot read properties of undefined (reading 'content')
    at mergeRequestBody (/home/dell/.npm/_npx/cb83394c13646cfe/node_modules/openapi-flattener/dist/flattener.js:36:40)
    at /home/dell/.npm/_npx/cb83394c13646cfe/node_modules/openapi-flattener/dist/flattener.js:66:17
    at Array.forEach (<anonymous>)
    at /home/dell/.npm/_npx/cb83394c13646cfe/node_modules/openapi-flattener/dist/flattener.js:51:47
    at /home/dell/.npm/_npx/cb83394c13646cfe/node_modules/call-me-maybe/src/maybe.js:9:28
    at processTicksAndRejections (node:internal/process/task_queues:78:11)```

**Comment by mattholden** [comment]
+1. Also, from the debug output, doesnt seem to be reading PATCH endpoints at all.

**Comment by mmgaggle** [comment]
Same - 

`/usr/lib/node_modules/openapi-flattener/dist/flattener.js:36
    var bodySchema = (_a = requestBody.content['application/json']) === null || _a === void 0 ? void 0 : _a.schema;
                                       ^

TypeError: Cannot read properties of undefined (reading 'content')
    at mergeRequestBody (/usr/lib/node_modules/openapi-flattener/dist/flattener.js:36:40)
    at /usr/lib/node_modules/openapi-flattener/dist/flattener.js:66:17
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/openapi-flattener/dist/flattener.js:51:47
    at /usr/lib/node_modules/openapi-flattener/node_modules/call-me-maybe/src/maybe.js:9:28
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.20.6`

**Comment by nallath** [comment]
Ran into the same issue :(
